- name: Download Alertmanager
  ansible.builtin.get_url:
    url: https://github.com/prometheus/alertmanager/releases/download/v0.27.0/alertmanager-0.27.0.linux-amd64.tar.gz
    dest: /tmp/alertmanager.tar.gz

- name: Unarchive Alertmanager
  ansible.builtin.unarchive:
    src: /tmp/alertmanager.tar.gz
    dest: /tmp
    remote_src: yes

- name: Ensure Alertmanager directory exists
  ansible.builtin.file:
    path: /tmp/alertmanager-0.27.0.linux-amd64
    state: directory

- name: Move alertmanager binary to /usr/local/bin
  ansible.builtin.shell: mv /tmp/alertmanager-0.27.0.linux-amd64/alertmanager /usr/local/bin/alertmanager
  become: true

- name: Set permissions for alertmanager binary
  ansible.builtin.file:
    path: /usr/local/bin/alertmanager
    mode: '0755'
    state: file



# - name: Create Prometheus alert rules file
#   ansible.builtin.template:
#     src: "alertmanager.j2"
#     dest: /etc/prometheus/alert.rules.yml
#     mode: '0644'
      
- name: Ensure /etc/alertmanager directory exists
  file:
    path: /etc/alertmanager
    state: directory
    mode: '0755'

    # Step 3: Configure Alertmanager
- name: Create Alertmanager configuration file
  ansible.builtin.template:
    src: "alertmanager2.j2"
    dest: /etc/alertmanager/alertmanager.yml
    mode: '0644'
      

    # Step 4: Configure systemd service for Alertmanager
- name: Create Alertmanager systemd service file
  ansible.builtin.template:
    src: "alertmanager3.j2"
    dest: /etc/systemd/system/alertmanager.service
    mode: '0644'


    # Step 5: Enable and restart Alertmanager service
- name: Reload systemd and start alertmanager
  ansible.builtin.systemd:
    name: alertmanager
    state: restarted
    enabled: true
